micronaut:
  application:
    name: products
  server:
    port: 8082
all:
  enabled: true
  sensitive: false

consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
